{"timestamp":"2025-09-11T03:25:02.878733","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-11T03:25:02.879422","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-11T03:25:13.376841","level":"warning","event":"Using Variable.get from `airflow.models` is deprecated.Please use `from airflow.sdk import Variable` instead","category":"DeprecationWarning","filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py","lineno":147,"logger":"py.warnings"}
{"timestamp":"2025-09-11T03:25:13.504557","level":"warning","event":"Skipping masking for a secret as it's too short (<5 chars)","logger":"airflow.sdk.execution_time.secrets_masker"}
{"timestamp":"2025-09-11T03:25:13.505252","level":"info","event":"Start loading data to BigQuery","logger":"root"}
{"timestamp":"2025-09-11T03:25:13.509065","level":"warning","event":"Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `from airflow.sdk import Connection` instead","category":"DeprecationWarning","filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py","lineno":471,"logger":"py.warnings"}
{"timestamp":"2025-09-11T03:25:13.593550","level":"info","event":"Connection Retrieved 'google_bq_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-09-11T03:25:14.020607","level":"info","event":"Defining table schema","logger":"root"}
{"timestamp":"2025-09-11T03:25:15.593442","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"BadRequest","exc_value":"400 Error while reading data, error message: Invalid timestamp microseconds value 1757574000000000000 of logical type TIMESTAMP_NANOS; in column 'date_time' File: gs://lake_project/weather_today_data/raw_data/2025-09-11/2025-09-11_weather_today.parquet; reason: invalid, location: gs://lake_project/weather_today_data/raw_data/2025-09-11/2025-09-11_weather_today.parquet, message: Error while reading data, error message: Invalid timestamp microseconds value 1757574000000000000 of logical type TIMESTAMP_NANOS; in column 'date_time' File: gs://lake_project/weather_today_data/raw_data/2025-09-11/2025-09-11_weather_today.parquet","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/etl_pipeline.py","lineno":75,"name":"task_load_gcs_to_bq"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py","lineno":1001,"name":"result"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py","lineno":261,"name":"result"}],"is_group":false,"exceptions":[]}]}
